"""
Phase 10 — Component 5: Clinical Safety & AI Output Validation
Verifies non-diagnostic safety gating, summary schema compliance,
source citation integrity, and FHIR bundle ABDM structural compliance.
"""
import os
import sys
import re
import pytest
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from app.main import app
from app.services.model_service import ModelService, PROHIBITED_DIAGNOSTIC_PATTERNS
from app.models.ai import ModelTaskResponse, ModelCapability

client = TestClient(app)


def _create_session(sid: str, gender: str = "MALE", age: int = 50) -> dict:
    return {
        "version": "1.0.0",
        "identity": {
            "session_id": sid,
            "facility_id": "SAFETY_TEST_FAC",
            "preferred_language": "en",
            "gender": gender,
            "age": age
        },
        "consent": {"scope": "INTAKE_AND_SUMMARY", "status": "GRANTED"}
    }


# ============================================================================
# 1. Non-Diagnostic Safety Gate
# ============================================================================

def test_safety_gate_rejects_autonomous_diagnosis():
    """
    The ModelService safety gate must detect and reject AI output that
    contains autonomous diagnostic assertions (per PRD Section 11.4).
    """
    ms = ModelService()

    # Simulate a dangerous model response with prohibited diagnostic language
    dangerous_response = ModelTaskResponse(
        success=True,
        capability=ModelCapability.SUMMARY_SYNTHESIS,
        provider_used="test",
        raw_response="Based on the symptoms, you have been diagnosed with acute myocardial infarction. You must take this medication immediately.",
        structured_payload={"chief_complaint": "chest pain"},
        confidence_score=0.95
    )

    is_safe, violation = ms._validate_safety(dangerous_response)
    assert is_safe is False, f"Safety gate should have rejected this output but didn't. Violation: {violation}"
    assert len(violation) > 0


def test_safety_gate_accepts_observational_summary():
    """
    The safety gate must allow proper observational clinical summaries that
    describe findings without making autonomous diagnoses.
    """
    ms = ModelService()

    safe_response = ModelTaskResponse(
        success=True,
        capability=ModelCapability.SUMMARY_SYNTHESIS,
        provider_used="test",
        raw_response="Patient reports chest pain for 2 hours. Pain is substernal, crushing in character, radiating to left arm. Onset was sudden. This presentation suggests possible cardiac etiology requiring urgent evaluation.",
        structured_payload={"chief_complaint": "chest pain"},
        confidence_score=0.90
    )

    is_safe, violation = ms._validate_safety(safe_response)
    assert is_safe is True, f"Safety gate incorrectly rejected safe output: {violation}"


def test_all_prohibited_patterns_compiled_correctly():
    """Verify all prohibited diagnostic patterns are valid regex expressions."""
    for pattern in PROHIBITED_DIAGNOSTIC_PATTERNS:
        try:
            re.compile(pattern)
        except re.error as e:
            pytest.fail(f"Invalid regex pattern in safety rules: '{pattern}' - {e}")


# ============================================================================
# 2. Summary Schema Compliance
# ============================================================================

def test_generated_summary_has_required_fields():
    """
    The summary generated by ModelService must contain the standard
    draft_status, provenance, and is_draft_for_clinician_review fields.
    """
    sid = "safety_schema_compliance"
    client.post("/api/v1/sessions/", json=_create_session(sid))

    # Interview
    client.get(f"/api/v1/sessions/{sid}/next-question")
    client.post(f"/api/v1/sessions/{sid}/answer", json={
        "question_id": "__CHIEF_COMPLAINT__",
        "free_text": "Persistent headache and fatigue"
    })

    # Generate summary
    sum_res = client.post(f"/api/v1/sessions/{sid}/ai/generate-summary")
    assert sum_res.status_code == 200
    payload = sum_res.json()
    assert payload["success"] is True

    structured = payload.get("structured_payload", {})
    # Verify required workflow fields
    assert "draft_status" in structured
    assert structured["draft_status"] == "PENDING"
    assert "provenance" in structured
    assert structured["provenance"]["review_status"] == "PENDING"
    assert structured["provenance"]["source_type"] == "AI_GENERATED"


def test_summary_retains_ai_provider_metadata():
    """
    Summary response must include the provider that generated it,
    latency metrics, and confidence score for audit trail.
    """
    sid = "safety_provider_meta"
    client.post("/api/v1/sessions/", json=_create_session(sid))

    client.get(f"/api/v1/sessions/{sid}/next-question")
    client.post(f"/api/v1/sessions/{sid}/answer", json={
        "question_id": "__CHIEF_COMPLAINT__",
        "free_text": "Stomach pain after eating"
    })

    sum_res = client.post(f"/api/v1/sessions/{sid}/ai/generate-summary")
    assert sum_res.status_code == 200
    data = sum_res.json()
    assert "provider_used" in data
    assert data["provider_used"] in ("colab_medgemma", "gemini", "mock")
    assert "latency_ms" in data


# ============================================================================
# 3. FHIR Bundle ABDM Structural Compliance
# ============================================================================

def test_fhir_bundle_type_is_document():
    """FHIR Bundle must be of type 'document' per ABDM NRCeS specifications."""
    sid = "safety_fhir_type"
    client.post("/api/v1/sessions/", json=_create_session(sid))

    # Complete flow
    client.get(f"/api/v1/sessions/{sid}/next-question")
    client.post(f"/api/v1/sessions/{sid}/answer", json={
        "question_id": "__CHIEF_COMPLAINT__",
        "free_text": "Breathing difficulty"
    })
    client.post(f"/api/v1/sessions/{sid}/ai/generate-summary")
    client.post(f"/api/v1/sessions/{sid}/summary/review", json={
        "action": "ACCEPTED",
        "clinician_id": "DR_FHIR_SAFETY"
    })
    client.post(f"/api/v1/sessions/{sid}/consent", json={
        "scope": "FULL_HIS_SHARE",
        "interaction_mode": "TOUCH_SCREEN"
    })

    bundle_res = client.post(f"/api/v1/sessions/{sid}/integration/prepare")
    assert bundle_res.status_code == 200
    bundle = bundle_res.json()["bundle"]
    assert bundle["type"] == "document"


def test_fhir_bundle_composition_is_entry_zero():
    """
    ABDM Chapter 33 mandates that the first entry in a Document Bundle
    must be a Composition resource (SNOMED: 371530004).
    """
    sid = "safety_fhir_composition_first"
    client.post("/api/v1/sessions/", json=_create_session(sid))

    client.get(f"/api/v1/sessions/{sid}/next-question")
    client.post(f"/api/v1/sessions/{sid}/answer", json={
        "question_id": "__CHIEF_COMPLAINT__",
        "free_text": "Cough with blood"
    })
    client.post(f"/api/v1/sessions/{sid}/ai/generate-summary")
    client.post(f"/api/v1/sessions/{sid}/summary/review", json={
        "action": "ACCEPTED",
        "clinician_id": "DR_ABDM_TEST"
    })
    client.post(f"/api/v1/sessions/{sid}/consent", json={
        "scope": "FULL_HIS_SHARE",
        "interaction_mode": "TOUCH_SCREEN"
    })

    bundle_res = client.post(f"/api/v1/sessions/{sid}/integration/prepare")
    assert bundle_res.status_code == 200
    entries = bundle_res.json()["bundle"]["entry"]
    assert len(entries) > 0
    assert entries[0]["resource"]["resourceType"] == "Composition"


def test_fhir_bundle_all_references_resolve():
    """
    Every internal URN reference (urn:uuid:...) in the FHIR Bundle
    must resolve to an actual entry in the bundle.
    """
    sid = "safety_fhir_ref_integrity"
    client.post("/api/v1/sessions/", json=_create_session(sid))

    client.get(f"/api/v1/sessions/{sid}/next-question")
    client.post(f"/api/v1/sessions/{sid}/answer", json={
        "question_id": "__CHIEF_COMPLAINT__",
        "free_text": "Skin rash and itching"
    })
    client.post(f"/api/v1/sessions/{sid}/ai/generate-summary")
    client.post(f"/api/v1/sessions/{sid}/summary/review", json={
        "action": "ACCEPTED",
        "clinician_id": "DR_REF_INTEGRITY"
    })
    client.post(f"/api/v1/sessions/{sid}/consent", json={
        "scope": "FULL_HIS_SHARE",
        "interaction_mode": "TOUCH_SCREEN"
    })

    bundle_res = client.post(f"/api/v1/sessions/{sid}/integration/prepare")
    assert bundle_res.status_code == 200
    bundle_data = bundle_res.json()
    assert bundle_data["is_valid"] is True, f"FHIR validation issues: {bundle_data.get('validation_issues')}"
